name: stagexl_benchmark
version: 0.0.1

environment:
  sdk: '>2.0.0'


dependencies:
  stagexl: ^1.4.4
  stagexl_spine: ^0.10.1
  shelf_router: ^0.7.2
  shelf_packages_handler: ^2.0.0
  shelf_proxy: ^0.1.0+7
  shelf_static: ^0.2.8
  uuid: ^2.0.4

dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.6.1 <3.0.0'