name: stagexl_benchmark
version: 0.0.1

environment:
  sdk: '>2.0.0'


dependencies:
  stagexl: ^1.4.4
  stagexl_spine: ^0.10.1

dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.6.1 <3.0.0'