name: pixi_dart_benchmark
version: 0.0.1

environment:
  sdk: '>2.0.0'

dependencies:
  pixi: ^4.8.1+1
  js: ^0.6.0
  shelf_router: ^0.7.2
  shelf_packages_handler: ^2.0.0
  shelf_proxy: ^0.1.0+7
  shelf_static: ^0.2.8
  uuid: ^2.0.4



dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.6.1 <3.0.0'