name: pixi_dart_benchmark
version: 0.0.1

environment:
  sdk: '>2.0.0'

dependencies:
  pixi: ^4.8.1+1
  js: ^0.6.0


dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.6.1 <3.0.0'